### ISSUE TITLE
How to run this model properly ?

### ISSUE THREAD

**Issue by Aneeshers** [shekkizh/Colorization.tensorflow#1]
So I installed all the libraries needed.... I run `python3 /Users/aneeshmuppidi/Downloads/Colorization.tensorflow-master/image_colorization.py --mode test  --data_dir Images/Test --model_dir /Users/aneeshmuppidi/Downloads/Colorization.tensorflow-master/imagenet-vgg-verydeep-19.mat  
`
(aneeshmuppidi is my username)

Then the program doesn't return anything.... it's like the program exited. What would be the proper way to run this?  Or does it save the output in a specific directory?

**Comment by shekkizh** [comment]
The mode has to be set to "train" to train the model. This is the default value for mode - so just running the command in your question without specifying mode argument should start training model.

**Comment by Aneeshers** [comment]
@shekkizh oh yea I forgot to include that  in that example.... But usually when I tried I would put the mode to test .... Does only train work ?

**Comment by shekkizh** [comment]
Train mode is to train the model. Test mode uses trained model to predict colored images on random images in the dataset.
Also please make a pull to get the latest code - I updated the code for Test mode 0629324dfe394c533fc231f95fc6126b9747b121
