### ISSUE TITLE
find these error

### ISSUE THREAD

**Issue by GANGREEK** [shekkizh/Colorization.tensorflow#4]
File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/PIL/Image.py", line 1695, in save
    fp = builtins.open(filename, "w+b")
IOError: [Errno 2] No such file or directory: 'logs/image_checkpoints/gt0.png'

**Comment by youyingyin** [comment]
io.imsave  could not create path which doesnot exsit.you should create 'logs' and 'image_checkpoints'  in advance
